//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureHorizonsBD
{


    public partial class About
    {

        /// <summary>
        /// lnkShareStory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink lnkShareStory;

        protected global::System.Web.UI.WebControls.Repeater rptCommunityReviews;
        protected global::System.Web.UI.WebControls.Label    lblNoReviews;
    }
}
